// EngineAssembly.jsx

import React from 'react';
import imageTopLeft from '../../assets/cv-axle-joint-repair-main.jpeg'; // Import your top-left image
import rightImage from '../../assets/axles.jpeg'; // Import your right-side image
import gifImage from '../../assets/sag-ev81-28.jpeg'; // Import your gif image
import styles from '../ABS/ABS.module.css'; // Import your modular CSS file
import rightImage1 from '../../assets/Copy of cv-axle-joint-repair-1.jpeg'; // Import your right-side image
import Imagetwo from '../../assets/rax2164d-2_1.jpeg'; // Import your gif image

const AXLEShaft = () => {
  return (
    <div className={styles.engineContainer}>
      {/* Top Row */}
      <div className={styles.topRow}>
        <img src={imageTopLeft} alt="Top Left" className={styles.topLeftImage} />
        <div className={styles.topRightContent}>
          <h1 className={styles.usedEngines}>AXLE SHAFT</h1>
          <button className={styles.instantQuoteButton}>Get An Instant Quote</button>
        </div>
      </div>

      {/* Content Row */}
      <div className={styles.contentRow}>
        <div className={styles.leftContent}>
          <h2>Axle Shaft </h2>
          <p>
            The unsung hero of your vehicle's drivetrain – the Axle Shaft. This crucial component is responsible for transferring power from the differential to the wheels, enabling your vehicle to move with precision and control. Let's delve into the world of Axle Shafts and explore why they are a vital link in the chain of your vehicle's mobility.
          </p>
          <p>

            The Axle Shaft may work silently, but its role in your vehicle's movement is undeniable. Regular maintenance and attention to its condition are key to ensuring a reliable and smooth driving experience. Trust in the efficiency and durability of a well-maintained Axle Shaft to keep your vehicle in motion with precision and control on every journey.
          </p>

        </div>
        <div className={styles.rightContent}>
          <img src={rightImage} alt="Right Image" className={styles.rightImage} />
        </div>
      </div>

      {/* Bottom Row */}
      <div className={styles.bottomRow}>
        <div className={styles.leftContent}>
          <img src={gifImage} alt="Gif Image" className={styles.gifImage} />
        </div>
        <div className={styles.rightContent}>
          <h2>
            Understanding the Axle Shaft:
          </h2>
          <p>

            The Axle Shaft is a rod-like component that connects the differential to the wheels, transmitting rotational power from the engine to the wheels to facilitate movement. In simple terms, it's the bridge that carries the torque generated by the engine to the wheels, ensuring a smooth and controlled ride.
          </p>
          <h4>
            Key Components of an Axle Shaft:
          </h4>
          <h6>  1. Splines:</h6><br />
          <p>

            The splines on the inner end of the Axle Shaft engage with the differential, allowing for the transfer of rotational force.

          </p>
          <h6>  2. CV Joints (Constant Velocity):</h6><br />
          <p>


            Many modern vehicles feature Constant Velocity joints on the outer ends of the Axle Shaft. These joints accommodate varying angles and speeds during wheel movement, ensuring a consistent velocity for smooth operation.

          </p>
          <h6>   3. Flange or Hub:</h6><br />
          <p>


            The outer end of the Axle Shaft connects to the wheel hub or flange, securing the shaft in place and facilitating the rotation of the wheel.

          </p>

        </div>
      </div>


      <div className={styles.contentRow}>
        <div className={styles.leftContent}>
          <h2>How the Axle Shaft Works:</h2>
          <h6>   Power Transfer:</h6><br />
          <p>



            The Axle Shaft receives rotational power from the differential, converting it into linear motion that drives the wheels.

          </p>
          <h6>
            Flexibility in Movement:</h6><br />
          <p>




            The presence of CV joints allows the Axle Shaft to flex and adapt to different angles and speeds, ensuring a constant velocity during turns and varying road conditions.

          </p>
          <h6>Wheel Rotation:</h6><br />
          <p>

            The outer end of the Axle Shaft connects to the wheel hub, enabling the rotation of the wheel in sync with the transmitted power.

          </p>

        </div>
        <div className={styles.rightContent}>
          <img src={rightImage1} alt="Right Image" className={styles.rightImage} />
        </div>
      </div>

      <div className={styles.lastBottomRow}>
        <div className={styles.leftContents}>
          <img src={Imagetwo} alt="Gif Image" className={styles.gifImage} />
        </div>
        <div className={styles.rightContents}>
          <h2>

            Advantages of a Well-Maintained Axle Shaft:

          </h2><h6>1. Efficient Power Transmission:</h6><br />
          <p>



            A properly functioning Axle Shaft ensures efficient and reliable transmission of power from the differential to the wheels, contributing to the overall performance of the vehicle.
          </p>
          <h6>2. Smooth Turns:</h6><br /><p>


            CV joints provide flexibility during turns, allowing the Axle Shaft to maintain a constant velocity and ensuring smooth handling and control.

          </p>
          <h6>
            3. Enhanced Traction:
          </h6>
          <br />
          <p>



            The Axle Shaft plays a crucial role in distributing power to both wheels, contributing to enhanced traction and stability, especially in challenging road conditions.

          </p>
          <h6>
            4. Longevity of Drivetrain:</h6><br /><p>



            Regular maintenance of the Axle Shaft helps prevent wear and tear, contributing to the longevity and durability of the entire drivetrain system.

          </p>


        </div>
      </div>

      <h2>
        Maintenance Tips for the Axle Shaft:
      </h2>
      <h6> Regular Inspections:</h6><br />
      <p>


        Regular Inspections:
        Periodically inspect the Axle Shaft for signs of damage, such as bends or cracks, and ensure that the splines and CV joints are in good condition.

      </p>
      <h6>
        CV Joint Lubrication:
      </h6>
      <br />
      <p>


        Maintain proper lubrication for CV joints to prevent friction and ensure their flexibility during movement.

      </p>
      <h6>
        Address Leaks:</h6>
      <br />
      <p>




        If there are signs of oil leaks around the Axle Shaft, address them promptly to prevent damage to the joints and other components.

      </p>
      <h6>  Balancing:</h6><br /><p>




        Ensure that the Axle Shaft is properly balanced to prevent vibrations and uneven wear on tires.

      </p>
      <h6>
        We at Quality Auto Salvage understand the pivotal role that the Axle Shaft plays in the dynamic operation of your vehicle, seamlessly transmitting power from the differential to the wheels. As your trusted partner in providing top-notch automotive components, we take pride in offering a diverse range of high-quality Axle Shafts. Here's why choosing Quality Auto Salvage for your Axle Shaft needs is a decision you can trust:

      </h6>
      <br />

      <h6>  1. Extensive Inventory:</h6><br /><p>




        Explore our extensive inventory, featuring a wide selection of Axle Shafts suitable for various makes and models. Whether you drive a compact car, a versatile SUV, or a rugged truck, we have the right Axle Shaft to match your specific vehicle requirements.

      </p>
      <h6> 2. Quality Assurance:</h6><br /><p>





        Quality is paramount in our mission. Each Axle Shaft in our inventory undergoes thorough inspection to ensure it meets or exceeds industry standards. We prioritize durability, precision engineering, and performance, providing you with Axle Shafts that deliver reliable power transmission.

      </p>
      <h6> 3. OEM Compatibility:</h6><br /><p>



        Our Axle Shafts are sourced with a focus on Original Equipment Manufacturer (OEM) compatibility. This ensures seamless integration with your vehicle's drivetrain, maintaining the original specifications and performance. Trust in the precise fit and function of our Axle Shafts for optimal power transfer.

      </p>
      <h6>   4. Cost-Effective Solutions:</h6><br /><p>



        At Quality Auto Salvage, we believe in offering budget-friendly alternatives without compromising quality. Our Axle Shafts provide a cost-effective solution for replacing or upgrading this essential component, allowing you to enjoy a smooth and powerful driving experience without exceeding your budget.

      </p>
      <h6>
        5. Expert Guidance:</h6><br /><p>

        Navigating the complexities of drivetrain components can be challenging. Our team of knowledgeable experts is here to assist you throughout the selection and installation process. Whether you have questions about compatibility, maintenance, or performance, we provide the guidance you need for a successful and reliable replacement.

      </p>
      <h6>6. Quick Availability:</h6><br /><p>



        We understand the urgency of your automotive needs. Our streamlined processes and efficient inventory management ensure that the Axle Shaft you require is readily available for prompt dispatch. Minimize downtime and get your vehicle back on the road swiftly with Quality Auto Salvage.

      </p>
      <h6>
        7. Transparency in Information:</h6><br /><p>

        Transparency is a core value at Quality Auto Salvage. Our product listings include detailed information about each Axle Shaft, empowering you to make well-informed decisions. We believe in providing you with the information you need to choose the right component for your vehicle.

      </p>
      <h6>  8. Environmental Responsibility:</h6><br /><p>


        By choosing a recycled Axle Shaft from Quality Auto Salvage, you contribute to sustainable and environmentally responsible practices. Reusing components aligns with our commitment to reducing the environmental impact of the automotive industry.

      </p>
      <h6>9. Customer-Centric Approach:</h6><br /><p>



        Our customers are our priority. We are dedicated to ensuring your satisfaction with our products and services. From selection to installation, our customer-centric approach aims to exceed your expectations and build a lasting relationship based on trust and reliability.

      </p>
      <h6>10. Secure Transactions:</h6><br /><p>


        Your online security is paramount to us. Quality Auto Salvage employs secure payment gateways and stringent data protection measures to ensure that your online transactions are safe and secure. Shop with confidence on our user-friendly online platform.

      </p>
      <p>
        Choose Quality Auto Salvage for your Axle Shaft needs, and experience the perfect blend of quality, affordability, and exceptional service. Trust us to be your reliable partner in keeping your vehicle in motion with a robust and efficient Axle Shaft.
      </p>
    </div>
  );
};

export default AXLEShaft;
